export default {
  LOGIN_SUBMIT: "@@LOGIN/SUBMIT",
  LOGIN_PASSWORD_ERROR: "@@LOGIN/PASSWORD_ERROR",
  LOGIN_COGNITO_ERROR: "@@LOGIN/COGNITO_ERROR",
  LOGIN_SUCCESS: "@@LOGIN/SUCCESS",

  SIGN_OUT: "SIGN_OUT",

  REGISTER_SUBMIT: "@@REGISTER/SUBMIT",
  REGISTER_USERNAME_ERROR: "@@REGISTER/USERNAME_ERROR",
  REGISTER_PASSWORD_ERROR: "@@REGISTER/PASSWORD_ERROR",
  REGISTER_COGNITO_ERROR: "@@REGISTER/COGNITO_ERROR"
};
